<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
<meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>짧.강.효.확</title>
<meta name="HandheldFriendly" content="true"/>
<meta name="MobileOptimized" content="320"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<c:import url="../template/common_css.jsp"></c:import> 
<c:import url="../template/header.jsp"></c:import>
<style>
	
	img[usemap] {
		border: none;
		height: auto;
		max-width: 90%;
		margin: 0 0 0 5%;
		width: auto;
	}
</style>	 
</head>
<body>

		<div class="container">
	 <div class="row justify-content-center mb-5 pb-3 ">
 	 <div class="col-md-12 heading-section ftco-animate text-center" style="line-height:5%">
 	 <h3 class="mb-1"><br>짧.강.효.확</h3><br><br>
					<p class="breadcrumbs">
						<span class="mr-2"><a href="/">짧지만 강하게!</a></span> <span>효과는 확실하게!</span>
					</p>
				</div>
			</div>
		</div>
	<c:if test="${sessionMember.roleDTO.roleName eq 'ADMIN'}"> 
	<a href="./add" class="detailAdd btn btn-primary" style="margin:0 0 0.5% 5%;">추가하기</a>
	</c:if> 
 <div class="bodyimages">	<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/resources/images/allbody.jpeg" usemap="#allbody" class="reponsive-img">
<map name="allbody">

	<c:forEach items="${body}" var="dto">
		<area href="/exercise/info?bodyNum=${dto.bodyNum}" title="${dto.bodyName}" coords="${dto.coordinate}" shape="rect" class="text-center">
	</c:forEach>
 
</map>
</div> 
<!-- <div class="bodyimages">	
<img src="/resources/images/allbody.jpeg" usemap="#allbody" class="reponsive-img">
<map name="allbody">

    <area target="" alt="face" title="faceVideo" href="/exercise/detail/info" coords="712,609,793,797" shape="rect">
    <area target="" alt="armfit" title="armfitVideo" href="/exercise/info" coords="722,901,981,964" shape="rect">
    <area target="" alt="arms" title="armsVideo" href="./detail/info" coords="515,936,718,1004" shape="rect">
    <area target="" alt="hip" title="hipVideo" href="/exercise/detail/hip" coords="484,1073,689,1141" shape="rect">
    <area target="" alt="legs" title="legsVideo" href="/exercise/detail/legs" coords="320,1122,427,1250" shape="rect">
    <area target="" alt="frontleg" title="frontlegVideo" href="/exercise/detail/frontleg" coords="584,1197,693,1326" shape="rect">
    <area target="" alt="inleg" title="inlegVideo" href="/exercise/detail/inleg" coords="735,1153,885,1275" shape="rect">
    <area target="" alt="upper" title="upperVideo" href="/exercise/detail/upperBody" coords="864,682,988,760" shape="rect">
    <area target="" alt="shoulder" title="shoulderVideo" href="/exercise/detail/shoulder" coords="1134,833,1473,911" shape="rect">
    <area target="" alt="back" title="backVideo" href="/exercise/detail/back" coords="1366,948,1485,1016" shape="rect">
    <area target="" alt="waist" title="waistVideo" href="/exercise/detail/waist" coords="1351,1022,1504,1085" shape="rect">
    <area target="" alt="bellyfat" title="bellyfatVideo" href="/exercise/detail/bellyfat" coords="1527,1027,1734,1094" shape="rect">
    <area target="" alt="stomach" title="stomachVideo" href="//exercise/detail/stomach" coords="1500,1097,1709,1160" shape="rect">
    <area target="" alt="sideleg" title="sidelegVideo" href="/exercise/detail/sideleg" coords="1259,1127,1417,1194" shape="rect">
    <area target="" alt="lower" title="lowerVideo" href="/exercise/detail/lowerBody" coords="1259,1127,1417,1194" shape="rect">
    <area target="" alt="series" title="seriesVideo" href="/exercise/detail/seires" coords="74,512,201,561" shape="rect">
    <area target="" alt="stretching" title="stretchingVideo" href="/exercise/detail/stertching" coords="75,583,198,707" shape="rect">
</map>
</div>   -->
	<!-- <script type="text/javascript" src="/resources/js/body.js"></script> -->
	<!-- End Save for Web Slices -->
	<!-- loader -->
	
<c:import url="../template/footer.jsp"></c:import>
<c:import url="../template/common_js.jsp"></c:import> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.min.js"></script>
<script>

$(document).ready(function(e) {
	$('img[usemap]').rwdImageMaps();
	
});

</script>
</body>
</html>


